"use client";

import {Suspense,useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {apiJson,formatDate,LedgerData,Scope} from "@/components/types";
import "./ledger.css";
import "../app-polish.css";

export default function LedgerPage(){return <Suspense fallback={<div className="page loading"><div className="spinner"/>Loading ledger…</div>}><LedgerView/></Suspense>}

function LedgerView(){const query=useSearchParams();const [scope,setScope]=useState<Scope>(query.get("scope")==="synthetic"?"synthetic":"real");const [data,setData]=useState<LedgerData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [auditOpen,setAuditOpen]=useState(false);
 const load=useCallback(()=>{setLoading(true);setError("");apiJson<LedgerData>(`/api/ledger?scope=${scope}`).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[scope]);useEffect(()=>{let active=true;apiJson<LedgerData>(`/api/ledger?scope=${scope}`).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[scope]);
 const changeScope=(next:Scope)=>{if(next===scope)return;setScope(next);setData(null);setLoading(true);setError("");};
 return <div className="page ledger-page"><div className="page-heading"><div><div className="eyebrow">Reviewed evidence / additions</div><h1 className="page-title">Housing event ledger</h1><p className="page-intro">A recorded addition appears here only after a human reviewer approves evidence for its identity, units, date, and prior counting. Coverage is limited to these seeded cases.</p></div><Link className="btn" href="/app">← Review queue</Link></div>
 <div className="segmented ledger-tabs" role="group" aria-label="Ledger data scope"><button className={scope==="real"?"active":""} aria-pressed={scope==="real"} onClick={()=>changeScope("real")}>Real data ledger</button><button className={scope==="synthetic"?"active":""} aria-pressed={scope==="synthetic"} onClick={()=>changeScope("synthetic")}>Synthetic sandbox ledger</button></div>
 {scope==="synthetic"&&<div className="notice"><strong>Isolated synthetic sandbox</strong>These entries are illustrative and are excluded from the real-data ledger and real-data exports.</div>}
 {error&&<div className="notice error" role="alert"><strong>Could not load the ledger.</strong>{error} <button className="btn btn-small" onClick={load}>Try again</button></div>}
 {loading?<div className="loading"><div className="spinner"/>Loading reviewed events…</div>:data&&<>
 <div className="ledger-summary panel"><div><span className="eyebrow">Verified additions within stated coverage</span><div className="ledger-total">{data.totalUnits}</div><p>Units across {data.events.length} reviewed housing event{data.events.length===1?"":"s"}. This is an additions-only result for the cases shown, not a citywide or net growth figure.</p></div><div className="ledger-summary-side"><div><strong>Coverage snapshot</strong><span>{formatDate(data.coverage.snapshotAt)}</span></div><div><strong>Source records</strong><span>{data.coverage.recordCount}</span></div><div><strong>Open cases</strong><span>{data.unresolvedProjects.length}</span></div></div></div>
 <div className="ledger-tools"><div><h2>Reviewed events</h2><p>Stable event identities prevent repeated imports or approvals from creating new ledger rows.</p></div><div className="btn-group"><a className="btn btn-small" href={`/api/export/ledger?scope=${scope}`} download={`countable-${scope}-ledger.csv`}>Download CSV ↓</a><a className="btn btn-small" href={`/api/export/report?scope=${scope}`} download={`countable-${scope}-evidence-report.md`}>Evidence report ↓</a></div></div>
 <div className="panel ledger-table-wrap"><table className="ledger-table"><thead><tr><th>Housing event</th><th>Additional units</th><th>Event date</th><th>Source / evidence</th><th>Review</th></tr></thead><tbody>{data.events.map(e=><tr key={e.id}><td><Link href={`/projects/${encodeURIComponent(e.projectId)}`}>{e.projectName}</Link><small>{e.buildingLabel||"Building unspecified"} · <span className="mono">{e.id}</span></small></td><td className="unit-cell">+{e.units}</td><td>{formatDate(e.eventDate)}</td><td><span className="source-references">{e.sourceRefs.join(", ")||"No source reference"}</span><small>{e.evidenceRefs.join(", ")||"No evidence reference"}</small></td><td><span className="pill green">Reviewed</span><small>{formatDate(e.decisionAt)}</small></td></tr>)}</tbody></table>{!data.events.length&&<div className="empty"><strong>No approved additions in this ledger yet.</strong><p>Review candidate events and supporting documents to create an auditable entry.</p><Link className="btn" href="/app">Open review queue</Link></div>}</div>
 <div className="ledger-lower"><section className="panel panel-pad"><div className="section-top"><h2>Unresolved cases</h2><span className="tiny muted">Remain visible alongside the ledger</span></div>{data.unresolvedProjects.length?<ul className="unresolved-list">{data.unresolvedProjects.map(p=><li key={p.id}><div><Link href={`/projects/${encodeURIComponent(p.id)}`}>{p.name}</Link><span>{p.reason}</span></div><Link className="back-link" href={`/projects/${encodeURIComponent(p.id)}`}>Review →</Link></li>)}</ul>:<p className="muted">No unresolved cases within this scope.</p>}</section><section className="panel panel-pad"><div className="section-top"><h2>Audit history</h2>{data.audit.length>4&&<button className="text-button" onClick={()=>setAuditOpen(!auditOpen)} aria-expanded={auditOpen}>{auditOpen?"Show less":"Show all"}</button>}</div>{data.audit.length?<ol className="ledger-audit">{(auditOpen?data.audit:data.audit.slice(0,4)).map(a=><li key={a.id}><div className="audit-time">{formatDate(a.at)}</div><div><strong>{a.action.replaceAll("_"," ")}</strong><span>{a.reason}</span><small>{a.targetType} · {a.targetId}</small></div></li>)}</ol>:<p className="muted">No review decisions have been recorded yet.</p>}</section></div>
 <div className="ledger-footnote">{data.coverage.note}</div>
 </>}
 </div>}
