"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import "./landing.css";

const sections = ["top", "story", "method", "receipt", "demand", "why-now", "roles", "proof", "demo"] as const;
const records = [
  { id: "PLAN-01", kind: "Whole project plan", claim: "24 planned", passage: "Two residential buildings are proposed with 24 apartments in total.", tone: "parent" },
  { id: "BLDG-A", kind: "Building A permit", claim: "8 units", passage: "Construction of Building A with eight new apartments.", tone: "building" },
  { id: "SPR-A", kind: "Sprinkler permit", claim: "8 repeated", passage: "Sprinkler work for Building A; eight apartments. References BLDG-A.", tone: "repeat" },
  { id: "BLDG-B", kind: "Building B permit", claim: "16 unconfirmed", passage: "Construction of Building B with sixteen proposed apartments.", tone: "pending" },
  { id: "OCC-A", kind: "Invented move-in approval", claim: "8 ready", passage: "Residential occupancy authorized for Building A's eight new apartments effective July 18, 2026.", tone: "reviewed" },
] as const;
const steps = [
  { title: "Group the paperwork", detail: "Countable suggests that the sprinkler form belongs with Building A because it names that building. Sharing an address or parcel would not be enough on its own.", evidence: "SPR-A names BLDG-A. Both forms refer to the same eight apartments.", label: "Suggested match" },
  { title: "Read each number in context", detail: "Countable highlights the exact words behind each number. The parent form describes a plan for 24 apartments; the Building A form describes eight of them. Neither proves the apartments are ready to use.", evidence: "“Construction of Building A with eight new apartments.”", label: "Quoted permit text" },
  { title: "Look for move-in approval", detail: "A construction permit allows work. Separate occupancy evidence can show when finished homes may legally be used. In this invented example, that evidence covers Building A only.", evidence: "“Residential occupancy authorized for Building A's eight new apartments effective July 18, 2026.”", label: "Invented occupancy passage" },
  { title: "Let a person verify it", detail: "A reviewer opens the original documents, confirms the building, eight homes and effective date, checks any conditions and asks whether these homes were counted before. Building B still has no move-in evidence.", evidence: "Reviewer approves Building A's eight; Building B remains unconfirmed.", label: "Illustrative reviewer decision" },
  { title: "Save a checkable count", detail: "Only after that review does Countable add eight homes to a list of approved results. It saves the document, quoted words, date and review decision so someone else can check the count.", evidence: "Building A + occupancy proof + reviewer approval → eight supported new homes.", label: "Result with its receipt" },
] as const;
function Tag({children}:{children:React.ReactNode}) { return <span className="section-tag">{children}</span>; }
function Scenario() { return <span className="scenario-label">Illustrative scenario · invented records</span>; }

export default function LandingPage() {
  const [selectedRecord,setSelectedRecord]=useState<(typeof records)[number]["id"]>("BLDG-A");
  const [comparison,setComparison]=useState<"overlap"|"reviewed">("overlap");
  const [step,setStep]=useState(0);
  const [presenting,setPresenting]=useState(false);
  const [presentIndex,setPresentIndex]=useState(0);
  const currentRecord=records.find(record=>record.id===selectedRecord)??records[1];
  const goTo=useCallback((index:number)=>{
    const bounded=Math.max(0,Math.min(index,sections.length-1));
    setPresentIndex(bounded);
    document.getElementById(sections[bounded])?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth",block:"start"});
  },[]);
  useEffect(()=>{
    if(!presenting)return;
    const onKeyDown=(event:KeyboardEvent)=>{
      if(["INPUT","TEXTAREA","SELECT"].includes((event.target as HTMLElement)?.tagName))return;
      if(event.key==="ArrowRight"||event.key==="ArrowDown"){event.preventDefault();goTo(presentIndex+1)}
      if(event.key==="ArrowLeft"||event.key==="ArrowUp"){event.preventDefault();goTo(presentIndex-1)}
      if(event.key==="Escape")setPresenting(false);
    };
    window.addEventListener("keydown",onKeyDown);
    return()=>window.removeEventListener("keydown",onKeyDown);
  },[presenting,presentIndex,goTo]);
  return <div className="landing">
    <section className="pitch-hero pitch-section" id="top" aria-labelledby="hero-title">
      <div className="pitch-container hero-grid">
        <div className="hero-copy"><Tag>AI Horizons 2026 · Housing Production Observatory</Tag><h1 id="hero-title">Every housing count has a <em>receipt.</em></h1><p className="hero-lede">How many new homes are actually ready for people to use? City paperwork can mention the same apartments several times without proving they are finished. Countable helps a person sort those records, check what is proven, and show why each home was counted.</p><div className="hero-actions"><a className="pitch-button pitch-button-light" href="#story">Start the story <span aria-hidden="true">↓</span></a><Link className="pitch-button pitch-button-outline" href="/app">Explore the working app <span aria-hidden="true">↗</span></Link></div><p className="hero-footnote">The “receipt” is the source document, the exact words, the date, and the reviewer&apos;s decision behind a count.</p></div>
        <div className="hero-visual" aria-label="Invented project forms leading to eight homes with move-in proof while Building B still needs evidence">
          <div className="visual-head"><Scenario/><span>01 / One project, many forms</span></div>
          <div className="visual-grid"><div className="visual-records">{records.map(record=><button type="button" key={record.id} className={`visual-card visual-${record.tone} ${selectedRecord===record.id?"selected":""}`} aria-pressed={selectedRecord===record.id} onClick={()=>setSelectedRecord(record.id)}><span className="visual-card-top"><span>{record.kind}</span><code>{record.id}</code></span><strong>{record.claim}</strong>{record.tone==="repeat"&&<small className="duplicate-note">Same eight as Building A</small>}</button>)}</div><div className="visual-join" aria-hidden="true"><span/><span/><span/></div><div className="visual-outcomes"><div className="visual-event"><span>Human checked · proof saved</span><strong>8</strong><small>homes supported as ready in this invented example</small><div className="event-stamp">✓ receipt attached</div></div><div className="visual-pending"><span>Building B</span><strong>16 still need proof</strong><small>Illustrative scenario · not counted</small></div></div></div>
          <div className="visual-passage" aria-live="polite"><span>Words from selected document · {currentRecord.id}</span><p>“{currentRecord.passage}”</p></div>
        </div>
      </div><div className="hero-baseline pitch-container"><span>Paperwork → original words → human check → supported count</span><span>Scroll to follow one case ↓</span></div>
    </section>

    <section className="pitch-section problem-section" id="story" aria-labelledby="problem-title"><div className="pitch-container story-grid"><div className="story-intro"><Tag>01 / The problem</Tag><h2 id="problem-title">Why can&apos;t we<br/>just add the<br/><em>numbers?</em></h2><p>One development can file a plan for the whole project, a building permit for each building, and separate paperwork for sprinklers. A building permit allows construction; it does not show that anyone can move in.</p><p className="story-example-intro">In this invented project, 24 apartments are planned: eight in Building A and 16 in B. The sprinkler form repeats A&apos;s same eight.</p><Scenario/></div><div className="comparison-panel"><div className="comparison-tabs" role="group" aria-label="Compare incorrect sum and reviewed interpretation"><button type="button" className={comparison==="overlap"?"active":""} aria-pressed={comparison==="overlap"} onClick={()=>setComparison("overlap")}>Add every number</button><button type="button" className={comparison==="reviewed"?"active":""} aria-pressed={comparison==="reviewed"} onClick={()=>setComparison("reviewed")}>Separate the facts</button></div>{comparison==="overlap"?<div className="comparison-body" key="overlap"><span className="micro-label">Illustrative scenario · the misleading sum</span><div className="bad-equation"><span>24 <small>whole plan</small></span><b>+</b><span>8 <small>Building A</small></span><b>+</b><span>8 <small>same A, sprinkler</small></span><b>+</b><span>16 <small>Building B</small></span><b>=</b><strong>56</strong></div><p className="comparison-callout"><span aria-hidden="true">×</span> Fifty-six counts some apartments twice and treats a plan as if it were finished homes.</p></div>:<div className="comparison-body" key="reviewed"><span className="micro-label">Illustrative scenario · three different facts</span><div className="supported-grid"><div><strong>24</strong><span>apartments planned across both buildings</span></div><div className="supported"><strong>8</strong><span>Building A homes ready after occupancy proof and review</span></div><div className="pending"><strong>16</strong><span>Building B homes still awaiting proof</span></div></div><p className="comparison-callout calm">The plan describes what might be built. Only separate occupancy evidence can support what is ready to use.</p></div>}</div></div></section>

    <section className="pitch-section method-section" id="method" aria-labelledby="method-title"><div className="pitch-container"><div className="section-heading"><div><Tag>02 / What Countable does</Tag><h2 id="method-title">How does a number<br/><em>become a fact?</em></h2></div><p>Countable groups related documents and shows the exact lines behind each number. A person then checks whether the homes are ready. A permit alone never adds homes to the result.</p></div><Scenario/><div className="method-grid"><div className="method-steps" role="group" aria-label="Countable workflow">{steps.map((item,index)=><button type="button" aria-pressed={step===index} className={step===index?"active":""} key={item.title} onClick={()=>setStep(index)}><span>{String(index+1).padStart(2,"0")}</span><strong>{item.title}</strong><span aria-hidden="true">↗</span></button>)}</div><div className="method-detail" aria-live="polite" key={step}><span className="micro-label">Illustrative scenario · {steps[step].label}</span><h3>{steps[step].title}</h3><p>{steps[step].detail}</p><blockquote>{steps[step].evidence}</blockquote><div className="detail-bottom"><span>The documents and decision stay with the result</span><span>{String(step+1).padStart(2,"0")} / 05</span></div></div></div></div></section>

    <section className="pitch-section receipt-section" id="receipt" aria-labelledby="receipt-title"><div className="pitch-container receipt-grid"><div><Tag>03 / The result</Tag><h2 id="receipt-title">Eight homes have proof.<br/>Sixteen still need it.</h2><p>In this invented example, Building A started with no apartments. A separate occupancy document says its eight new apartments may legally be used starting July 18, 2026. A person checks that document and approves the eight. We do not have the same proof for Building B, so its 16 remain unknown—not zero.</p><Scenario/></div><div className="receipt-card"><div className="receipt-card-top"><span>Illustrative result</span><span>Reviewed</span></div><div className="receipt-number">+8 <small>new homes supported<br/>in this scenario</small></div><dl><div><dt>Building</dt><dd>Building A · BLDG-A</dd></div><div><dt>Proof</dt><dd>Invented occupancy passage · OCC-A</dd></div><div><dt>Date</dt><dd>July 18, 2026</dd></div><div><dt>Decision</dt><dd>Reviewer checked the building, eight homes, date, conditions and whether they were already counted</dd></div></dl><p className="receipt-assumption">This example assumes no homes existed at Building A before construction. A real case would need that checked.</p><div className="receipt-pending">Building B · 16 planned homes · still awaiting proof</div></div></div></section>

    <section className="pitch-section demand-section" id="demand" aria-labelledby="demand-title"><div className="pitch-container"><div className="demand-heading"><div><Tag>04 / Why this exists</Tag><h2 id="demand-title">Pittsburgh researchers faced the same problem.</h2></div><p>The paperwork puzzle is real. The City Controller&apos;s team had to sort overlapping housing records by hand and called for better public information.</p></div><div className="demand-grid"><article><span className="demand-index">01 / Duplicate records</span><h3>One project appeared many times.</h3><p>Researchers found several permits for the same project, unit totals that disagreed, and missing addresses. They checked the descriptions and occupancy certificates with City Planning to work out what was actually built.</p><a href="https://www.pittsburghpa.gov/files/assets/city/v/1/controller/documents/special-report-inclusionary-zoning-6.10.25.pdf#page=18" target="_blank" rel="noreferrer">Controller report · p. 18 ↗</a></article><article><span className="demand-index">02 / Manual work</span><h3>They called for a clearer public view.</h3><p>The Controller said organizing permit records takes considerable manual work and recommended an ongoing public dashboard showing completed homes—not just paperwork filed.</p><a href="https://www.pittsburghpa.gov/files/assets/city/v/1/controller/documents/special-report-inclusionary-zoning-6.10.25.pdf#page=29" target="_blank" rel="noreferrer">Controller report · pp. 28–31 ↗</a></article><article><span className="demand-index">03 / Hard to search</span><h3>A simple search can miss records.</h3><p>WPRDC says permit descriptions are entered by hand and vary in format. Pittsburgh also changed its application type in 2024, so finding building work requires searching both old and new categories.</p><a href="https://data.wprdc.org/dataset/pli-permits" target="_blank" rel="noreferrer">WPRDC dataset notes ↗</a></article></div><p className="demand-caveat">This shows a real public-data problem. It does not mean the City uses Countable or that anyone has bought it.</p></div></section>

    <section className="pitch-section why-section" id="why-now" aria-labelledby="why-title"><div className="pitch-container why-grid"><div><Tag>05 / Why now</Tag><h2 id="why-title">The City now has to publish a clearer answer.</h2><p>Pittsburgh law calls for a public housing-construction dashboard by December 31, 2026. Its underlying data must be open to audit, so a total can be traced back to the records behind it. The law treats a new home as constructed when it is legally available for people to use—not merely when a building permit is issued.</p><a href="https://pittsburgh.legistar.com/LegislationDetail.aspx?FullText=1&GUID=C2C4ED09-2E63-4E96-A4D5-49EB8F47947D&ID=7994765&Options=&Search=" target="_blank" rel="noreferrer" className="source-citation">Read Ordinance 13 / File 2026-0427 ↗</a><p className="why-disclaimer">Countable is an independent prototype covering a small sample and additions only. It is not the City&apos;s dashboard or a claim that we meet every reporting requirement.</p></div><div className="deadline-display"><span>Public reporting deadline</span><strong>DEC<br/>31<span>, 2026</span></strong><p>City construction dashboard due by the end of 2026</p></div></div></section>

    <section className="pitch-section roles-section" id="roles" aria-labelledby="roles-title"><div className="pitch-container"><div className="section-heading"><div><Tag>06 / Who decides?</Tag><h2 id="roles-title">The software helps.<br/>A person is responsible.</h2></div><p>Countable separates a useful suggestion from an approved number. Here is what each part does for Building A&apos;s eight apartments.</p></div><div className="roles-grid"><article><span>01 / Suggestion</span><h3>AI points to possible matches.</h3><p>When enabled, it can suggest that the sprinkler form belongs with Building A and highlight the line mentioning eight apartments.</p><div className="role-chip">A suggestion is never counted</div></article><article><span>02 / Human decision</span><h3>A reviewer checks the originals.</h3><p>They decide whether the forms describe the same homes, inspect move-in approval and any conditions, and record why they accept or reject a result.</p><div className="role-chip">The reason is saved</div></article><article><span>03 / Counting rule</span><h3>Code writes one approved result.</h3><p>After review, it saves Building A&apos;s eight with its date and proof. It leaves Building B&apos;s 16 out until they have their own evidence.</p><div className="role-chip">Only reviewed homes are added</div></article></div><p className="roles-note">This local demo needs no AI key: it shows prepared suggestions and applies the review and counting rules. A server key enables live AI suggestions, but the model still cannot approve a count.</p></div></section>

    <section className="pitch-section proof-section" id="proof" aria-labelledby="proof-title"><div className="pitch-container proof-grid"><div className="proof-copy"><Tag>07 / Now the real records</Tag><h2 id="proof-title">Does the same problem show up in Pittsburgh?</h2><p>Yes. The app holds a selected set of 12 real Pittsburgh permit records. For Bedford Phase 2A, one application describes a plan for 70 apartments across eight buildings. Building A3&apos;s permit mentions nine apartments; its sprinkler permit mentions the same nine again. These pages help explain the project, but they do not show that anyone may move into those apartments.</p><div className="proof-notice"><strong>What we can say today</strong><span>This snapshot has no occupancy document. Countable therefore shows no verified new homes from these records yet. That means the proof is missing—not that zero homes were built.</span></div><div className="proof-actions"><Link className="pitch-button pitch-button-dark" href="/projects/development-10c?showcase=1">Explore the Bedford case ↗</Link><a href="https://data.wprdc.org/dataset/pli-permits" target="_blank" rel="noreferrer" className="source-citation">Original permit dataset ↗</a><Link href="/methodology" className="source-citation">How we count ↗</Link></div></div><div className="real-record-stack" aria-label="Three actual permit records from the selected WPRDC snapshot"><div><span>Plan for the whole development</span><code>BDA-2024-03554</code><strong>70 apartments / 8 buildings</strong></div><div><span>Permit for one building · A3</span><code>BP-2024-13992</code><strong>9 apartments</strong></div><div><span>Sprinkler permit for A3</span><code>SSP-2025-03861</code><strong>Same 9, not 9 more</strong></div><p>12 selected records from a September 26, 2026 snapshot · not a citywide count</p></div></div></section>

    <section className="pitch-section demo-section" id="demo" aria-labelledby="demo-title"><div className="pitch-container"><div className="demo-heading"><div><Tag>08 / Try the working app</Tag><h2 id="demo-title">Open the case.<br/>Read the words.<br/><em>See what&apos;s missing.</em></h2><p>Open the real Bedford case to read the original permits and see why no home is approved for counting yet. The separate, clearly labeled practice case shows a completed review with its saved proof. Practice results never change the real count.</p><Link className="pitch-button pitch-button-light" href="/app">Open the working app ↗</Link><div className="demo-shortcuts"><Link href="/projects/development-10c?showcase=1">Inspect real Bedford →</Link><Link href="/projects/development-10c-sandbox?showcase=1&step=8">See a practice approval →</Link></div></div><div className="demo-side-note"><span>LIVE APP PREVIEW</span><span>5 selected real cases · 12 cached records</span></div></div><div className="live-preview"><iframe title="Live preview of Countable review queue" src="/app" loading="lazy" tabIndex={-1}/><div className="preview-overlay"><Link href="/app">Open the review app <span aria-hidden="true">↗</span></Link></div></div></div></section>

    <div className="present-dock" aria-label="Optional presentation controls">{presenting?<><button type="button" onClick={()=>goTo(presentIndex-1)} disabled={presentIndex===0} aria-label="Previous section">←</button><span>Present · {presentIndex+1}/{sections.length}</span><button type="button" onClick={()=>goTo(presentIndex+1)} disabled={presentIndex===sections.length-1} aria-label="Next section">→</button><button type="button" onClick={()=>setPresenting(false)} aria-label="Exit presentation mode">×</button></>:<button type="button" onClick={()=>{setPresenting(true);goTo(0)}}>Present ↗</button>}</div>
  </div>;
}
