"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import "./landing.css";

const sections = ["top", "story", "method", "receipt", "demand", "why-now", "roles", "proof", "demo"] as const;
const records = [
  { id: "BDA-2024-03554", kind: "Bedford development application", claim: "70 in eight buildings", passage: "IN PHASE 2A OF BEDFORD DEVELOPMENT, 70 NEW UNITS IN 8 NEW BUILDINGS, ON SITE PARKING WITH PLAY AREAS", tone: "parent" },
  { id: "BP-2024-13992", kind: "Building A3 permit", claim: "9 apartments", passage: "CONSTRUCTION OF 3 STORY APARTMENT BUILDING NO A3 WITH 9 APARTMENTS (3) TWO BEDROOM AND (6) THREE BEDROOM UNITS", tone: "building" },
  { id: "SSP-2025-03861", kind: "A3 sprinkler permit", claim: "Same 9 apartments", passage: "SPRINKLER SYSTEM FOR 3 STORY APARTMENT BUILDING NO A3 WITH 9 APARTMENTS (3) TWO BEDROOM AND (6) THREE BEDROOM UNITS INCLUDES NEW PIPING, SPRINKLER HEADS AND FDC. INSTALL NEW 12\" UNDERGROUND FIRE MAIN IN RELATION TO WORK PERFORMED UNDER BP-2024-13992", tone: "repeat" },
  { id: "BDA-2026-05107", kind: "Temporary-use application", claim: "Work still pending", passage: "PENDING COMPLETING OF PERMIT BP-2024-13992, TEMPORARY USE OF 3 STORY APARTMENT BUILDING-ALL WORK TO BE COMPLETE EXCEPT LAND-OPS, STORM-WATER, AND DOMI PERMITS.", tone: "pending" },
] as const;
const steps = [
  { title: "Group related forms", detail: "The A3 sprinkler description explicitly names building permit BP-2024-13992. Countable proposes a link for a person to check; a shared parcel alone would not prove that two forms describe the same building.", evidence: "IN RELATION TO WORK PERFORMED UNDER BP-2024-13992", label: "Source-backed proposed link" },
  { title: "Read each number in context", detail: "The development application describes 70 units across eight buildings. A3's building permit describes nine in one building. Its sprinkler permit repeats those nine. These are overlapping claims, not separate batches of finished homes.", evidence: "70 NEW UNITS IN 8 NEW BUILDINGS · BUILDING NO A3 WITH 9 APARTMENTS", label: "Words from real permits" },
  { title: "Check what status means", detail: "One related temporary-use application is marked Completed, but its description says work is still pending under the A3 permit. A status label cannot replace the original document or prove legal occupancy.", evidence: "PENDING COMPLETING OF PERMIT BP-2024-13992, TEMPORARY USE ...", label: "Real status and description" },
  { title: "Look for move-in proof", detail: "A reviewer must find a linked occupancy document, read any conditions, and confirm which homes and date it covers. No such document is included in this selected permit snapshot.", evidence: "No occupancy document in the selected 12-record snapshot.", label: "Evidence gap" },
  { title: "Keep the answer honest", detail: "Countable keeps the permit claims visible and leaves the addition unresolved. If a reviewer later adds sufficient original evidence, the app can save the document, quoted words, date and decision with an approved result.", evidence: "A3: nine apartments described · verified additions unresolved.", label: "Current result" },
] as const;
function Tag({children}:{children:React.ReactNode}) { return <span className="section-tag">{children}</span>; }
function SourceCohort() { return <span className="scenario-label">Real Pittsburgh permit records · selected snapshot</span>; }

export default function LandingPage() {
  const [selectedRecord,setSelectedRecord]=useState<(typeof records)[number]["id"]>("BP-2024-13992");
  const [comparison,setComparison]=useState<"overlap"|"reviewed">("overlap");
  const [step,setStep]=useState(0);
  const [presenting,setPresenting]=useState(false);
  const [presentIndex,setPresentIndex]=useState(0);
  const currentRecord=records.find(record=>record.id===selectedRecord)??records[1];
  const goTo=useCallback((index:number)=>{
    const bounded=Math.max(0,Math.min(index,sections.length-1));
    setPresentIndex(bounded);
    document.getElementById(sections[bounded])?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth",block:"start"});
  },[]);
  useEffect(()=>{
    if(!presenting)return;
    const onKeyDown=(event:KeyboardEvent)=>{
      if(["INPUT","TEXTAREA","SELECT"].includes((event.target as HTMLElement)?.tagName))return;
      if(event.key==="ArrowRight"||event.key==="ArrowDown"){event.preventDefault();goTo(presentIndex+1)}
      if(event.key==="ArrowLeft"||event.key==="ArrowUp"){event.preventDefault();goTo(presentIndex-1)}
      if(event.key==="Escape")setPresenting(false);
    };
    window.addEventListener("keydown",onKeyDown);
    return()=>window.removeEventListener("keydown",onKeyDown);
  },[presenting,presentIndex,goTo]);
  return <div className="landing">
    <section className="pitch-hero pitch-section" id="top" aria-labelledby="hero-title">
      <div className="pitch-container hero-grid">
        <div className="hero-copy"><Tag>AI Horizons 2026 · Housing Production Observatory</Tag><h1 id="hero-title">Every housing count has a <em>receipt.</em></h1><p className="hero-lede">How many new homes are actually ready for people to use? Real Pittsburgh permits can mention the same apartments several times without proving they are finished. Countable helps a person sort those records, find what is missing, and explain why a number can or cannot be counted.</p><div className="hero-actions"><a className="pitch-button pitch-button-light" href="#story">Start with the real records <span aria-hidden="true">↓</span></a><Link className="pitch-button pitch-button-outline" href="/app">Explore the working app <span aria-hidden="true">↗</span></Link></div><p className="hero-footnote">A “receipt” means the original document, exact words, date and reviewer decision behind an approved count. The Bedford case still needs that proof.</p></div>
        <div className="hero-visual" aria-label="Four real Bedford permit records with overlapping unit claims; occupancy proof is missing">
          <div className="visual-head"><SourceCohort/><span>01 / One project, many forms</span></div>
          <div className="visual-grid"><div className="visual-records">{records.map(record=><button type="button" key={record.id} className={`visual-card visual-${record.tone} ${selectedRecord===record.id?"selected":""}`} aria-pressed={selectedRecord===record.id} onClick={()=>setSelectedRecord(record.id)}><span className="visual-card-top"><span>{record.kind}</span><code>{record.id}</code></span><strong>{record.claim}</strong>{record.tone==="repeat"&&<small className="duplicate-note">Explicitly references the A3 building permit</small>}</button>)}</div><div className="visual-join" aria-hidden="true"><span/><span/><span/></div><div className="visual-outcomes"><div className="visual-event"><span>What the permits establish</span><strong>?</strong><small>verified new homes in this selected snapshot</small><div className="event-stamp">Occupancy proof still needed</div></div><div className="visual-pending"><span>Building A3</span><strong>9 described in permits</strong><small>Do not count as ready yet</small></div></div></div>
          <div className="visual-passage" aria-live="polite"><span>Words from selected public record · {currentRecord.id}</span><p>“{currentRecord.passage}”</p></div>
        </div>
      </div><div className="hero-baseline pitch-container"><span>Paperwork → original words → human check → supported count</span><span>Scroll to follow one case ↓</span></div>
    </section>

    <section className="pitch-section problem-section" id="story" aria-labelledby="problem-title"><div className="pitch-container story-grid"><div className="story-intro"><Tag>01 / The problem</Tag><h2 id="problem-title">Why can&apos;t we<br/>just add the<br/><em>numbers?</em></h2><p>In Bedford Phase 2A, a real development application describes 70 new units across eight buildings. One building permit describes nine apartments in A3. A sprinkler permit repeats those nine and names the A3 building permit.</p><p className="story-example-intro">These forms describe different parts of the same project. A permit allows work; it does not show when anyone may legally move in.</p><SourceCohort/></div><div className="comparison-panel"><div className="comparison-tabs" role="group" aria-label="Compare incorrect sum and source-backed interpretation"><button type="button" className={comparison==="overlap"?"active":""} aria-pressed={comparison==="overlap"} onClick={()=>setComparison("overlap")}>Add every number</button><button type="button" className={comparison==="reviewed"?"active":""} aria-pressed={comparison==="reviewed"} onClick={()=>setComparison("reviewed")}>Separate the facts</button></div>{comparison==="overlap"?<div className="comparison-body" key="overlap"><span className="micro-label">Real Bedford records · the misleading sum</span><div className="bad-equation"><span>70 <small>whole project</small></span><b>+</b><span>9 <small>Building A3</small></span><b>+</b><span>9 <small>A3 sprinkler form</small></span><b>=</b><strong>88</strong></div><p className="comparison-callout"><span aria-hidden="true">×</span> Eighty-eight would add overlapping paperwork and mistake a development plan for finished homes.</p></div>:<div className="comparison-body" key="reviewed"><span className="micro-label">Real Bedford records · three different facts</span><div className="supported-grid"><div><strong>70</strong><span>units described for the whole development</span></div><div className="supported"><strong>9</strong><span>apartments described in A3&apos;s building permit</span></div><div className="pending"><strong>?</strong><span>new homes verified as ready to use from these records</span></div></div><p className="comparison-callout calm">The sprinkler form repeats A3&apos;s nine. No occupancy document is included in this snapshot, so completed additions are unresolved.</p></div>}</div></div></section>

    <section className="pitch-section method-section" id="method" aria-labelledby="method-title"><div className="pitch-container"><div className="section-heading"><div><Tag>02 / What Countable does</Tag><h2 id="method-title">How does a number<br/><em>become a fact?</em></h2></div><p>Countable groups related documents and shows the exact lines behind each number. A person checks what the documents actually establish. The app keeps the answer unresolved when the needed proof is missing.</p></div><SourceCohort/><div className="method-grid"><div className="method-steps" role="group" aria-label="Countable workflow">{steps.map((item,index)=><button type="button" aria-pressed={step===index} className={step===index?"active":""} key={item.title} onClick={()=>setStep(index)}><span>{String(index+1).padStart(2,"0")}</span><strong>{item.title}</strong><span aria-hidden="true">↗</span></button>)}</div><div className="method-detail" aria-live="polite" key={step}><span className="micro-label">Bedford source review · {steps[step].label}</span><h3>{steps[step].title}</h3><p>{steps[step].detail}</p><blockquote>{steps[step].evidence}</blockquote><div className="detail-bottom"><span>Source claims stay separate from verified additions</span><span>{String(step+1).padStart(2,"0")} / 05</span></div></div></div></div></section>

    <section className="pitch-section receipt-section" id="receipt" aria-labelledby="receipt-title"><div className="pitch-container receipt-grid"><div><Tag>03 / The honest result</Tag><h2 id="receipt-title">The permits name homes.<br/>They cannot prove move-in.</h2><p>Bedford&apos;s application says 70 units are part of the development plan. A3&apos;s permit says nine apartments belong to that building. Neither document tells us when those apartments became legally available to use. This selected snapshot has no occupancy document, so Countable leaves the addition unresolved. Missing proof is not proof that no homes were built.</p><SourceCohort/></div><div className="receipt-card"><div className="receipt-card-top"><span>Bedford A3 · current evidence</span><span>Unresolved</span></div><div className="receipt-number">? <small>new homes verified<br/>as ready to use</small></div><dl><div><dt>Building</dt><dd>A3 · BP-2024-13992</dd></div><div><dt>Permit claim</dt><dd>Nine apartments in the building description</dd></div><div><dt>Overlap</dt><dd>SSP-2025-03861 repeats those nine</dd></div><div><dt>Missing</dt><dd>Linked occupancy document, effective date, conditions and reviewer decision</dd></div></dl><p className="receipt-assumption">This is a result about evidence available in the selected records. It is not a statement about all homes built at Bedford or in Pittsburgh.</p><div className="receipt-pending">No verified addition from these records yet · number built remains unknown</div></div></div></section>

    <section className="pitch-section demand-section" id="demand" aria-labelledby="demand-title"><div className="pitch-container"><div className="demand-heading"><div><Tag>04 / Why this exists</Tag><h2 id="demand-title">Pittsburgh researchers faced the same problem.</h2></div><p>The paperwork puzzle is real. The City Controller&apos;s team had to sort overlapping housing records by hand and called for better public information.</p></div><div className="demand-grid"><article><span className="demand-index">01 / Duplicate records</span><h3>One project appeared many times.</h3><p>Researchers found several permits for the same project, unit totals that disagreed, and missing addresses. They checked the descriptions and occupancy certificates with City Planning to work out what was actually built.</p><a href="https://www.pittsburghpa.gov/files/assets/city/v/1/controller/documents/special-report-inclusionary-zoning-6.10.25.pdf#page=18" target="_blank" rel="noreferrer">Controller report · p. 18 ↗</a></article><article><span className="demand-index">02 / Manual work</span><h3>They called for a clearer public view.</h3><p>The Controller said organizing permit records takes considerable manual work and recommended an ongoing public dashboard showing completed homes—not just paperwork filed.</p><a href="https://www.pittsburghpa.gov/files/assets/city/v/1/controller/documents/special-report-inclusionary-zoning-6.10.25.pdf#page=29" target="_blank" rel="noreferrer">Controller report · pp. 28–31 ↗</a></article><article><span className="demand-index">03 / Hard to search</span><h3>A simple search can miss records.</h3><p>WPRDC says permit descriptions are entered by hand and vary in format. Pittsburgh also changed its application type in 2024, so finding building work requires searching both old and new categories.</p><a href="https://data.wprdc.org/dataset/pli-permits" target="_blank" rel="noreferrer">WPRDC dataset notes ↗</a></article></div><p className="demand-caveat">This shows a real public-data problem. It does not mean the City uses Countable or that anyone has bought it.</p></div></section>

    <section className="pitch-section why-section" id="why-now" aria-labelledby="why-title"><div className="pitch-container why-grid"><div><Tag>05 / Why now</Tag><h2 id="why-title">The City now has to publish a clearer answer.</h2><p>Pittsburgh law calls for a public housing-construction dashboard by December 31, 2026. Its underlying data must be open to audit, so a total can be traced back to the records behind it. The law treats a new home as constructed when it is legally available for people to use—not merely when a building permit is issued.</p><a href="https://pittsburgh.legistar.com/LegislationDetail.aspx?FullText=1&GUID=C2C4ED09-2E63-4E96-A4D5-49EB8F47947D&ID=7994765&Options=&Search=" target="_blank" rel="noreferrer" className="source-citation">Read Ordinance 13 / File 2026-0427 ↗</a><p className="why-disclaimer">Countable is an independent prototype covering a small sample and additions only. It is not the City&apos;s dashboard or a claim that we meet every reporting requirement.</p></div><div className="deadline-display"><span>Public reporting deadline</span><strong>DEC<br/>31<span>, 2026</span></strong><p>City construction dashboard due by the end of 2026</p></div></div></section>

    <section className="pitch-section roles-section" id="roles" aria-labelledby="roles-title"><div className="pitch-container"><div className="section-heading"><div><Tag>06 / Who decides?</Tag><h2 id="roles-title">The software helps.<br/>A person is responsible.</h2></div><p>Countable separates a useful suggestion from an approved number. In Bedford, the permit claims stay visible while the completed-home count remains unresolved.</p></div><div className="roles-grid"><article><span>01 / Suggestion</span><h3>AI points to possible matches.</h3><p>When enabled, it can suggest that the A3 sprinkler filing belongs with A3&apos;s building permit and show the line that names the permit.</p><div className="role-chip">A suggestion is never counted</div></article><article><span>02 / Human decision</span><h3>A reviewer checks the originals.</h3><p>They decide whether the forms describe the same homes, seek an occupancy document, inspect its conditions and record their reason.</p><div className="role-chip">A missing document stays missing</div></article><article><span>03 / Counting rule</span><h3>Code protects the result.</h3><p>It keeps A3&apos;s nine as a permit claim. Without linked move-in proof, an event date and reviewer approval, the app cannot mark the addition verified.</p><div className="role-chip">Unresolved is not zero built</div></article></div><p className="roles-note">This local demo needs no AI key: it shows source-backed proposals and applies the review and counting rules. A server key enables live AI suggestions, but the model still cannot approve a count.</p></div></section>

    <section className="pitch-section proof-section" id="proof" aria-labelledby="proof-title"><div className="pitch-container proof-grid"><div className="proof-copy"><Tag>07 / The source trail</Tag><h2 id="proof-title">Even “Completed” needs context.</h2><p>The selected 12-record snapshot includes an A3 temporary-use application marked Completed. Its own description says work under the building permit was still pending. That is a useful lead to investigate, not an occupancy certificate or a reason to add nine homes to the count.</p><div className="proof-notice"><strong>The next real evidence step</strong><span>Check the current case and any original documents in OneStopPGH, then search the City&apos;s separate occupancy records. An occupancy document must be linked to A3 and reviewed before its homes can be counted.</span></div><div className="proof-actions"><Link className="pitch-button pitch-button-dark" href="/projects/development-10c?showcase=1">Explore the Bedford case ↗</Link><a href="https://onestoppgh.pittsburghpa.gov/" target="_blank" rel="noreferrer" className="source-citation">Search OneStopPGH ↗</a><a href="https://data.wprdc.org/dataset/pli-permits" target="_blank" rel="noreferrer" className="source-citation">Original permit dataset ↗</a><Link href="/methodology" className="source-citation">How we count ↗</Link></div></div><div className="real-record-stack" aria-label="Four actual records from the selected WPRDC snapshot"><div><span>Development application · source claim</span><code>BDA-2024-03554</code><strong>70 units / 8 buildings</strong></div><div><span>Building permit · A3</span><code>BP-2024-13992</code><strong>9 apartments</strong></div><div><span>Sprinkler permit · repeats A3</span><code>SSP-2025-03861</code><strong>Same 9, not 9 more</strong></div><div><span>Temporary-use application · status Completed</span><code>BDA-2026-05107</code><strong>Description says work pending</strong></div><p>Only four of eight child-building permits are in this selected snapshot · no occupancy document included</p></div></div></section>

    <section className="pitch-section demo-section" id="demo" aria-labelledby="demo-title"><div className="pitch-container"><div className="demo-heading"><div><Tag>08 / Try the working app</Tag><h2 id="demo-title">Open the case.<br/>Read the words.<br/><em>See what&apos;s missing.</em></h2><p>Open Bedford to inspect the actual permit descriptions, proposed links and open evidence questions. The app keeps the count unresolved until a reviewer can attach sufficient original proof. Every record in the showcase comes from the selected public snapshot.</p><Link className="pitch-button pitch-button-light" href="/app">Open the working app ↗</Link><div className="demo-shortcuts"><Link href="/projects/development-10c?showcase=1">Inspect real Bedford →</Link><Link href="/ledger?scope=real">See the evidence ledger →</Link></div></div><div className="demo-side-note"><span>LIVE APP PREVIEW</span><span>5 selected real cases · 12 cached records</span></div></div><div className="live-preview"><iframe title="Live preview of Countable review queue" src="/app" loading="lazy" tabIndex={-1}/><div className="preview-overlay"><Link href="/app">Open the review app <span aria-hidden="true">↗</span></Link></div></div></div></section>

    <div className="present-dock" aria-label="Optional presentation controls">{presenting?<><button type="button" onClick={()=>goTo(presentIndex-1)} disabled={presentIndex===0} aria-label="Previous section">←</button><span>Present · {presentIndex+1}/{sections.length}</span><button type="button" onClick={()=>goTo(presentIndex+1)} disabled={presentIndex===sections.length-1} aria-label="Next section">→</button><button type="button" onClick={()=>setPresenting(false)} aria-label="Exit presentation mode">×</button></>:<button type="button" onClick={()=>{setPresenting(true);goTo(0)}}>Present ↗</button>}</div>
  </div>;
}
